# This is a basic workflow to help you get started with Actions
name: Demo Basic - Build

# Controls when the workflow will run
on:
  # Triggers the workflow any push event
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Specify GITHUB_TOKEN scope for the entire workflow
permissions: read-all

# Set default values for run jobs
defaults:
  run:
    shell: bash

env:
  CI_BUILD: true

jobs:
  checks:
    name: Checks & Test
    uses: theappbusiness/github-actions-demo-workflows/.github/workflows/reusable-checks.yml@main

  # Deploy build artefacts to target locations
  deploy:
    name: Deploy Builds 🚀
    runs-on: ubuntu-latest
    needs: [checks]

    steps:
      - name: Checks for your app
        run: |
          {
            echo "### Deployment Summary"
            echo ""
            echo "This Github Action demo is now complete"
            echo "Thank you"
            echo ""
            echo "Enjoy your friday 🎉"
          } >> $GITHUB_STEP_SUMMARY
          
