# This is a basic workflow to help you get started with Actions
name: Demo Basic - Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push main and any release/ branches
  push:
    branches:
      - 'main'
      - 'release/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Specify GITHUB_TOKEN scope for the entire workflow
permissions: read-all

# Set default values for run jobs
defaults:
  run:
    shell: bash

env:
  CI_BUILD: true

jobs:
  build:
    name: App Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Android Runner
        uses: ./.github/actions/setup-android-runner

      # Gradle execution - clean
      - name: Clean
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean

      # Gradle execution - assemble with gradle scan and publish
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :app:assemble --scan
        env:        
          SIGNING_KEYSTORE_STORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_STORE_PASSWORD }}
          SIGNING_KEYSTORE_KEY_ALIAS: ${{ secrets.SIGNING_KEYSTORE_KEY_ALIAS }}
          SIGNING_KEYSTORE_KEY_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_KEY_PASSWORD }}
